-- FITRIX initial schema.
--
-- The app is local-first: everything lives on the device and is synced here
-- when the user is signed in. Every row belongs to one user and row level
-- security only ever exposes the caller's own rows.

-- Keeps updated_at current on every update (used for last-write-wins sync).
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Profile (one row per user, created by the app after sign-in)
-- ---------------------------------------------------------------------------
create table public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  name text not null default '' check (char_length(name) <= 100),
  surname text not null default '' check (char_length(surname) <= 100),
  age smallint check (age between 5 and 120),
  weight_kg numeric(5, 1) check (weight_kg between 20 and 400),
  height_cm numeric(5, 1) check (height_cm between 80 and 260),
  language text not null default 'en' check (language in ('en', 'ru', 'uz', 'es')),
  onboarding_complete boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Workout plans ("Chest and Biceps"). id is the app's id (built-in plans use
-- readable ids like 'gym-chest-biceps', user-made ones a uuid), unique per
-- user. Deleting a plan sets deleted_at so other devices learn about it.
-- ---------------------------------------------------------------------------
create table public.workout_templates (
  user_id uuid not null references auth.users (id) on delete cascade,
  id text not null check (char_length(id) <= 100),
  sport text not null check (
    sport in ('gym', 'fitness', 'cycling', 'running', 'football', 'winterSports')
  ),
  name text not null check (char_length(name) between 1 and 100),
  focus text not null default '' check (char_length(focus) <= 100),
  estimated_minutes integer not null default 60 check (estimated_minutes between 0 and 1440),
  -- [{ name, sets: [{ previousKg, previousReps, kg, reps, done }] }]
  exercises jsonb not null default '[]'::jsonb check (jsonb_typeof(exercises) = 'array'),
  position integer not null default 0,
  deleted_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (user_id, id)
);

create trigger workout_templates_set_updated_at
before update on public.workout_templates
for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Finished workouts (append-only history). id is generated by the app so
-- retries are idempotent.
-- ---------------------------------------------------------------------------
create table public.completed_workouts (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  template_id text not null check (char_length(template_id) <= 100),
  name text not null check (char_length(name) between 1 and 100),
  sport text not null check (
    sport in ('gym', 'fitness', 'cycling', 'running', 'football', 'winterSports')
  ),
  started_at timestamptz not null,
  finished_at timestamptz not null,
  -- Only completed sets, same shape as workout_templates.exercises
  exercises jsonb not null default '[]'::jsonb check (jsonb_typeof(exercises) = 'array'),
  created_at timestamptz not null default now(),
  check (finished_at >= started_at)
);

create index completed_workouts_user_finished_idx
  on public.completed_workouts (user_id, finished_at desc);

-- ---------------------------------------------------------------------------
-- Felix chat messages. topic is 'app' (general assistant / onboarding chat)
-- or a sport name for the trainer chats. id is the app's message id.
-- ---------------------------------------------------------------------------
create table public.chat_messages (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  topic text not null check (
    topic in ('app', 'gym', 'fitness', 'cycling', 'running', 'football', 'winterSports')
  ),
  role text not null check (role in ('user', 'assistant')),
  content text not null check (char_length(content) <= 8000),
  is_quick_reply boolean not null default false,
  sent_at timestamptz not null,
  created_at timestamptz not null default now()
);

create index chat_messages_user_topic_sent_idx
  on public.chat_messages (user_id, topic, sent_at);

-- ---------------------------------------------------------------------------
-- Row level security: each user sees and changes only their own rows.
-- ---------------------------------------------------------------------------
alter table public.profiles enable row level security;
alter table public.workout_templates enable row level security;
alter table public.completed_workouts enable row level security;
alter table public.chat_messages enable row level security;

create policy "Own profile: read" on public.profiles
  for select to authenticated using ((select auth.uid()) = id);
create policy "Own profile: create" on public.profiles
  for insert to authenticated with check ((select auth.uid()) = id);
create policy "Own profile: update" on public.profiles
  for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id);

create policy "Own plans: read" on public.workout_templates
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Own plans: create" on public.workout_templates
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Own plans: update" on public.workout_templates
  for update to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);

create policy "Own history: read" on public.completed_workouts
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Own history: create" on public.completed_workouts
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Own history: delete" on public.completed_workouts
  for delete to authenticated using ((select auth.uid()) = user_id);

create policy "Own messages: read" on public.chat_messages
  for select to authenticated using ((select auth.uid()) = user_id);
create policy "Own messages: create" on public.chat_messages
  for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "Own messages: delete" on public.chat_messages
  for delete to authenticated using ((select auth.uid()) = user_id);
